import { requireAdmin } from "../_lib/auth.js";
import { addActivity, createId, findObjectById, findTrashObjectById, hashText, json, objectId, objectName, readJsonObject, sanitizeAlias, sanitizeFilename, sanitizeFolder, updateObjectMetadata, writeJsonObject } from "../_lib/files.js";
async function aliasOwner(bucket,alias){if(!alias)return null;return readJsonObject(bucket,`_mx/aliases/${alias}.json`,null)}
async function setAlias(bucket,oldAlias,alias,id){if(oldAlias&&oldAlias!==alias)await bucket.delete(`_mx/aliases/${oldAlias}.json`);if(alias)await writeJsonObject(bucket,`_mx/aliases/${alias}.json`,{id,alias,updatedAt:new Date().toISOString()})}
async function moveToTrash(bucket,object){const source=await bucket.get(object.key);if(!source)throw new Error("File body not found.");const id=objectId(object),name=objectName(object),key=`_mx/trash/${id}/${name}`;await bucket.put(key,source.body,{httpMetadata:source.httpMetadata,customMetadata:{...(source.customMetadata||{}),trashedAt:new Date().toISOString()}});await bucket.delete(object.key)}
async function restoreFromTrash(bucket,object){const source=await bucket.get(object.key);if(!source)throw new Error("Trash file body not found.");const id=objectId(object),name=objectName(object),metadata={...(source.customMetadata||{})};delete metadata.trashedAt;await bucket.put(`${id}/${name}`,source.body,{httpMetadata:source.httpMetadata,customMetadata:metadata});await bucket.delete(object.key)}
async function listAll(bucket){const objects=[];let cursor;do{const page=await bucket.list({limit:1000,cursor,include:["httpMetadata","customMetadata"]});objects.push(...page.objects);cursor=page.truncated?page.cursor:undefined}while(cursor);return objects}
export async function onRequest({request,env}){const denied=requireAdmin(request,env);if(denied)return denied;if(!env.FILES)return json({error:"R2 binding FILES is not configured."},500);const url=new URL(request.url),action=url.searchParams.get("action")||"";try{
if(request.method==="GET"&&action==="activity"){const page=await env.FILES.list({prefix:"_mx/activity/",limit:100}),items=[];for(const obj of page.objects.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,60)){const item=await readJsonObject(env.FILES,obj.key,null);if(item)items.push(item)}return json({items})}
if(request.method==="POST"&&action==="folder"){const body=await request.json(),name=sanitizeFolder(body.name);if(!name)return json({error:"Folder name is required."},400);const id=sanitizeAlias(name)||createId(),folder={id,name,createdAt:new Date().toISOString()};await writeJsonObject(env.FILES,`_mx/folders/${id}.json`,folder);await addActivity(env.FILES,"folder.created",{name});return json({ok:true,folder})}
if(request.method==="POST"&&action==="folder-delete"){const body=await request.json(),name=sanitizeFolder(body.name);if(!name)return json({error:"Folder name is required."},400);const objects=await listAll(env.FILES),folderObject=objects.find(o=>o.key.startsWith("_mx/folders/")&&o.key.endsWith(".json")&&o.customMetadata?.name===name);let folderKey=folderObject?.key||"";if(!folderKey){for(const object of objects.filter(o=>o.key.startsWith("_mx/folders/")&&o.key.endsWith(".json"))){const value=await readJsonObject(env.FILES,object.key,null);if(value?.name===name){folderKey=object.key;break}}}if(!folderKey)return json({error:"Folder not found."},404);const affected=objects.filter(o=>!o.key.startsWith("_mx/")&&o.customMetadata?.folder===name);for(const object of affected)await updateObjectMetadata(env.FILES,object,{folder:""});await env.FILES.delete(folderKey);await addActivity(env.FILES,"folder.deleted",{name,movedFiles:affected.length});return json({ok:true,movedFiles:affected.length})}
if(request.method==="POST"&&action==="update"){const body=await request.json(),object=await findObjectById(env.FILES,body.id);if(!object)return json({error:"File not found."},404);const current=object.customMetadata||{},changes={};if(Object.prototype.hasOwnProperty.call(body,"folder"))changes.folder=sanitizeFolder(body.folder);if(Object.prototype.hasOwnProperty.call(body,"isPublic"))changes.public=body.isPublic?"1":"0";if(Object.prototype.hasOwnProperty.call(body,"expiresAt"))changes.expiresAt=String(body.expiresAt||"").slice(0,40);if(Object.prototype.hasOwnProperty.call(body,"password"))changes.passwordHash=body.password?await hashText(body.password):"";if(Object.prototype.hasOwnProperty.call(body,"alias")){const alias=sanitizeAlias(body.alias);if(alias){const existing=await aliasOwner(env.FILES,alias);if(existing?.id&&existing.id!==body.id)return json({error:"That custom link is already in use."},409)}await setAlias(env.FILES,current.alias||"",alias,body.id);changes.alias=alias}const result=await updateObjectMetadata(env.FILES,object,changes,body.name||null);await addActivity(env.FILES,"file.updated",{id:body.id,name:body.name||objectName(object)});return json({ok:true,key:result.key})}
if(request.method==="POST"&&action==="trash"){const{id}=await request.json(),object=await findObjectById(env.FILES,id);if(!object)return json({error:"File not found."},404);const alias=object.customMetadata?.alias;if(alias)await env.FILES.delete(`_mx/aliases/${alias}.json`);await moveToTrash(env.FILES,object);await addActivity(env.FILES,"file.trashed",{id,name:objectName(object)});return json({ok:true})}
if(request.method==="POST"&&action==="restore"){const{id}=await request.json(),object=await findTrashObjectById(env.FILES,id);if(!object)return json({error:"Trash item not found."},404);const alias=object.customMetadata?.alias;if(alias)await setAlias(env.FILES,"",alias,id);await restoreFromTrash(env.FILES,object);await addActivity(env.FILES,"file.restored",{id,name:objectName(object)});return json({ok:true})}
if(request.method==="POST"&&action==="purge"){const{id}=await request.json(),object=await findTrashObjectById(env.FILES,id);if(!object)return json({error:"Trash item not found."},404);await env.FILES.delete(object.key);await addActivity(env.FILES,"file.deleted",{id,name:objectName(object)});return json({ok:true})}
if(request.method==="POST"&&action==="url"){const body=await request.json();let sourceUrl;try{sourceUrl=new URL(body.url)}catch{return json({error:"Enter a valid URL."},400)}if(!/^https?:$/.test(sourceUrl.protocol))return json({error:"Only http/https URLs are supported."},400);const response=await fetch(sourceUrl.toString(),{redirect:"follow"});if(!response.ok||!response.body)return json({error:`Remote server returned ${response.status}.`},400);const urlName=decodeURIComponent(sourceUrl.pathname.split("/").pop()||"download"),name=sanitizeFilename(body.name||urlName||"download"),id=createId(),key=`${id}/${name}`;await env.FILES.put(key,response.body,{httpMetadata:{contentType:response.headers.get("content-type")||"application/octet-stream"},customMetadata:{originalName:name,createdAt:new Date().toISOString(),public:"1"}});await addActivity(env.FILES,"file.remote_upload",{id,name,url:sourceUrl.toString()});return json({ok:true,id,url:`/f/${id}`})}
return json({error:"Unsupported action."},405)}catch(error){return json({error:error?.message||String(error)},500)}}
