import { requireAdmin } from "../_lib/auth.js";
import { addActivity, createId, json, sanitizeFilename } from "../_lib/files.js";
const MAX_FILE_SIZE=10*1024*1024*1024;
export async function onRequest(context){const{request,env}=context,denied=requireAdmin(request,env);if(denied)return denied;if(!env.FILES)return json({error:"R2 binding FILES is not configured."},500);const url=new URL(request.url),action=url.searchParams.get("action");try{
if(request.method==="POST"&&action==="create"){const body=await request.json(),name=sanitizeFilename(body.name),type=String(body.type||"application/octet-stream").slice(0,150),size=Number(body.size||0);if(!Number.isFinite(size)||size<=0)return json({error:"Invalid file size."},400);if(size>MAX_FILE_SIZE)return json({error:"This build accepts files up to 10 GiB."},413);const id=createId(),key=`${id}/${name}`,upload=await env.FILES.createMultipartUpload(key,{httpMetadata:{contentType:type},customMetadata:{originalName:name,createdAt:new Date().toISOString(),public:"1",folder:String(body.folder||"").slice(0,80)}});return json({id,key,uploadId:upload.uploadId,directUrl:`${url.origin}/f/${id}`})}
if(request.method==="PUT"&&action==="part"){const key=url.searchParams.get("key"),uploadId=url.searchParams.get("uploadId"),partNumber=Number(url.searchParams.get("partNumber"));if(!key||!uploadId||!Number.isInteger(partNumber)||partNumber<1||!request.body)return json({error:"Missing upload part parameters."},400);const upload=env.FILES.resumeMultipartUpload(key,uploadId);return json(await upload.uploadPart(partNumber,request.body))}
if(request.method==="POST"&&action==="complete"){const key=url.searchParams.get("key"),uploadId=url.searchParams.get("uploadId");if(!key||!uploadId)return json({error:"Missing upload completion parameters."},400);const body=await request.json(),parts=Array.isArray(body.parts)?body.parts:[];if(!parts.length)return json({error:"No uploaded parts were supplied."},400);parts.sort((a,b)=>a.partNumber-b.partNumber);const upload=env.FILES.resumeMultipartUpload(key,uploadId),object=await upload.complete(parts),id=key.split("/",1)[0];await addActivity(env.FILES,"file.uploaded",{id,name:key.split("/").slice(1).join("/"),size:object.size});return json({ok:true,id,key:object.key,size:object.size,etag:object.httpEtag,directUrl:`${url.origin}/f/${id}`})}
if(request.method==="DELETE"&&action==="abort"){const key=url.searchParams.get("key"),uploadId=url.searchParams.get("uploadId");if(!key||!uploadId)return json({error:"Missing abort parameters."},400);await env.FILES.resumeMultipartUpload(key,uploadId).abort();return new Response(null,{status:204})}
return json({error:"Unsupported upload action."},405)}catch(error){return json({error:error?.message||String(error)},500)}}
